//! # Parsing tables
//!
//! Parsing tables extracted from files generated by `Bison` for `C` language.
//! This file was generated by dedicated tool, do not modify it manually.

use dsntk_common::Result;

/// Types of tokens returned by lexer.
#[derive(Clone)]
pub enum TokenType {
  YyEmpty = -2,
  YyEof = 0,
  YyError = 256,
  YyUndef = 257,
  StartExpression = 258,
  StartBoxedExpression = 259,
  StartTextualExpression = 260,
  StartTextualExpressions = 261,
  StartUnaryTests = 262,
  StartSimpleExpression = 263,
  StartSimpleExpressions = 264,
  StartSimpleValue = 265,
  StartRangeLiteral = 266,
  At = 267,
  Not = 268,
  Colon = 269,
  Comma = 270,
  Every = 271,
  For = 272,
  LeftBrace = 273,
  Null = 274,
  RightArrow = 275,
  Of = 276,
  List = 277,
  Range = 278,
  Context = 279,
  Then = 280,
  Function = 281,
  External = 282,
  If = 283,
  RightBrace = 284,
  Return = 285,
  Some = 286,
  Numeric = 287,
  String = 288,
  Boolean = 289,
  Satisfies = 290,
  Else = 291,
  Or = 292,
  And = 293,
  Eq = 294,
  Ne = 295,
  Lt = 296,
  Le = 297,
  Gt = 298,
  Ge = 299,
  Between = 300,
  BetweenAnd = 301,
  In = 302,
  Minus = 303,
  Plus = 304,
  Mul = 305,
  Div = 306,
  Exp = 307,
  Instance = 309,
  Name = 310,
  NameDateTime = 311,
  BuiltInTypeName = 312,
  LeftParen = 313,
  RightParen = 314,
  LeftBracket = 315,
  RightBracket = 316,
  Ellipsis = 317,
  Dot = 318,
}

/// Kinds of symbols recognized by parser.
#[allow(clippy::enum_variant_names)]
pub enum SymbolKind {
  YyEmpty = -2,
  YyEof = 0,
  YyError = 1,
  YyUndef = 2,
  YyAccept = 64,
}

/// (tbd)
pub const YY_PACT_N_INF: i16 = -194;

/// (tbd)
pub const YY_TABLE_N_INF: i16 = -123;

/// (tbd)
pub const YY_FINAL: usize = 69;

/// (tbd)
pub const YY_LAST: i16 = 1235;

/// (tbd)
pub const YY_N_TOKENS: usize = 64;

/// `YY_TRANSLATE[TOKEN-NUM]` - symbol number corresponding to TOKEN-NUM as returned by lexer.
pub const YY_TRANSLATE: [i8; 319] = [
  0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
  32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
];

/// `YY_PACT[STATE-NUM]` - index in YY_TABLE of the portion describing STATE-NUM.
pub const YY_PACT: [i16; 345] = [
  1224, 549, 16, 549, 549, -194, 596, 596, -8, 148, 40, 8, -194, -194, -194, -194, -12, 549, -194, -194, -194, -194, 549, 549, 549, 549, 549, 549, 549, -194, -9, 257, 643, 308,
  1046, -194, -194, -194, -194, 355, -194, -194, -194, -194, -194, 643, -194, 1046, 58, 23, -194, 405, 549, 22, 1073, -194, -194, 125, -194, 78, -194, 49, -194, -194, 132, 33,
  134, -194, 180, -194, -194, -194, -194, 35, -194, 883, -194, 50, -194, -194, -194, -194, -194, -194, 120, -194, -194, 938, 55, 216, 762, 61, -194, -194, 73, 549, 549, 549, 549,
  549, 549, 549, 549, -194, 690, 549, 549, 549, 549, 549, 130, 452, 549, 98, -194, 737, -194, 109, 762, 549, 97, 549, 855, -194, -194, 28, 106, 549, 549, 549, 549, 549, 596, 149,
  -194, -194, 135, -194, 140, 141, -194, 142, -194, -194, -194, 126, 176, 199, 161, 187, 207, 170, -194, -194, -194, -194, 128, 212, -26, 549, 194, 452, -194, -194, 549, -194,
  -194, -194, -194, 1099, 1124, 1149, 1149, 1149, 1149, 1149, 1149, 549, 257, 731, 1163, 1163, 96, 96, 120, -194, 217, -194, 793, -194, -194, 0, -194, 965, -194, -194, -194, -194,
  -194, 549, 549, -194, 20, 121, 21, 137, 147, -194, -194, -194, -194, -194, -194, -194, -194, -194, 549, -194, -194, 549, -194, -194, 54, -194, -194, 549, 227, -194, 502, -194,
  911, 549, -194, 762, 992, 824, -194, 197, 549, 549, -194, -194, 188, -194, -194, -194, 186, -194, 69, 1046, -194, 204, 1046, -194, 206, 128, 1046, -194, 549, 1046, -194, 2, 549,
  1046, -194, 549, 549, 205, 218, 219, 221, -194, -194, -194, 1046, 793, 217, 0, -194, -194, 249, 208, 549, 549, -194, 197, 1046, 211, -194, -194, 1046, 731, 209, -194, -194, 215,
  234, -194, -194, -194, 245, -194, 1046, 1019, -194, -194, -194, -194, 197, 197, 265, -194, 17, -194, 260, 197, -194, 549, 2, 241, 243, -194, 215, -194, -194, -194, 24, -194,
  1046, -194, -194, -194, 197, 17, 197, -194, -194, -194, -194, -194, -194, -194, 197, 24, -194,
];

/// `YY_DEF_ACT[STATE-NUM]` - default reduction number in state STATE-NUM.
/// Performed when YY_TABLE does not specify something else to do.
/// Zero means the default is an error.
pub const YY_DEF_ACT: [u8; 345] = [
  0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 22, 17, 97, 90, 0, 0, 20, 91, 92, 93, 0, 0, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 2, 12, 13, 48, 74, 0, 47, 89, 16, 14, 15, 0, 3, 0, 13, 13, 5, 0,
  0, 49, 0, 8, 65, 89, 87, 67, 9, 122, 10, 88, 0, 0, 0, 11, 0, 1, 94, 152, 145, 0, 155, 0, 152, 86, 72, 73, 68, 69, 70, 71, 41, 95, 76, 86, 0, 107, 86, 0, 106, 77, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 81, 82, 75, 0, 0, 0, 0, 53, 57, 7, 55, 41, 0, 0, 0, 0, 0, 0, 0, 0, 179, 180, 0, 169, 0, 0, 170, 0, 174, 175, 168, 0, 0, 151, 0, 0,
  144, 0, 99, 105, 104, 98, 0, 0, 0, 0, 0, 0, 50, 78, 0, 109, 108, 80, 79, 26, 27, 28, 29, 30, 31, 32, 33, 0, 0, 35, 37, 36, 38, 39, 40, 42, 49, 111, 0, 46, 112, 0, 113, 0, 44,
  83, 84, 85, 51, 0, 0, 121, 37, 36, 38, 39, 40, 66, 181, 182, 171, 173, 172, 176, 177, 178, 0, 152, 153, 0, 145, 146, 0, 102, 100, 0, 165, 157, 0, 158, 0, 0, 96, 0, 0, 86, 34, 0,
  0, 0, 119, 118, 0, 116, 114, 45, 0, 56, 0, 23, 150, 0, 18, 143, 0, 0, 101, 163, 0, 167, 156, 0, 0, 21, 110, 0, 0, 0, 0, 0, 0, 123, 124, 43, 115, 0, 0, 0, 54, 187, 0, 0, 0, 0,
  103, 0, 166, 0, 160, 159, 19, 25, 0, 125, 127, 0, 138, 120, 117, 188, 0, 183, 154, 148, 147, 164, 161, 58, 0, 0, 0, 129, 0, 137, 0, 0, 184, 0, 0, 0, 0, 133, 0, 135, 132, 130, 0,
  185, 149, 162, 126, 128, 0, 0, 0, 141, 140, 139, 186, 134, 136, 131, 0, 0, 142,
];

/// `YY_P_GOTO[NTERM-NUM]`
pub const YY_P_GOTO: [i16; 81] = [
  -194, -194, -194, -1, 285, 15, -194, -194, -194, -194, -194, 173, -194, -189, -194, 287, 162, -194, -194, -194, -194, 30, 294, -194, 1, -194, -194, -194, -194, 81, 51, -194,
  -194, -194, 62, 143, -194, 65, 31, -194, 34, 6, -193, -194, -194, -194, -194, -11, -194, -23, -194, -194, -29, -194, 101, -194, -194, -194, -194, -75, -194, -194, -194, -194,
  -194, -194, -194, 4, -194, 36, -194, -194, -194, -194, -194, 190, -194, -194, -194, -194, -194,
];

/// `YY_DEF_GOTO[NTERM-NUM]`
pub const YY_DEF_GOTO: [i16; 81] = [
  0, 10, 51, 77, 35, 36, 72, 76, 71, 177, 237, 50, 123, 124, 236, 59, 60, 37, 38, 39, 116, 88, 56, 40, 41, 161, 42, 73, 155, 156, 224, 157, 43, 92, 166, 189, 190, 191, 244, 192,
  241, 272, 273, 308, 309, 334, 311, 312, 332, 324, 314, 315, 337, 342, 149, 150, 151, 254, 304, 146, 147, 148, 251, 44, 158, 228, 261, 289, 318, 229, 285, 260, 67, 68, 144, 138,
  248, 281, 327, 338, 299,
];

/// `YY_TABLE[YY_PACT[STATE-NUM]]` - what to do in state STATE-NUM.
/// If positive, shift that token.
/// If negative, reduce the rule whose number is the opposite.
/// If `YY_TABLE_N_INF`, syntax error.
pub const YY_TABLE: [i16; 1236] = [
  34, 160, 47, 47, 11, 54, 54, 57, 57, 63, 246, 247, 58, 58, 58, 242, 75, 287, 48, 49, -60, -61, -122, -52, 19, 20, 21, 84, -64, 226, 87, 90, 322, 227, 14, -60, -61, -122, 119,
  335, 69, 70, 16, -64, 118, 133, 74, 61, 30, 85, 122, 125, 78, 79, 80, 81, 82, 83, -4, 243, 323, 288, 91, 94, 152, 134, 135, 336, 153, 117, 107, 108, 109, 109, 110, 110, 45, 292,
  111, 111, 112, 112, 110, 113, 113, 126, 111, 153, 112, 136, 154, 113, 305, 132, 169, 170, 171, 172, 173, 174, 175, 176, 279, 179, 180, 181, 182, 183, 184, 154, 188, 193, 126,
  113, 90, 319, 320, 163, 47, 94, 84, -59, 326, 167, 280, -88, 202, 203, 204, 205, 206, 54, 201, 57, 49, 168, -59, -62, 58, 339, -88, 341, 250, 222, 133, 91, 133, -63, 109, 343,
  110, 185, -62, 194, 111, 199, 112, 223, 230, 113, 188, 61, -63, 233, 134, 135, 134, 135, 195, 196, 197, 107, 108, 109, 110, 110, 234, 235, 111, 111, 112, 112, 208, 113, 113,
  213, 214, 215, 136, 109, 136, 110, 133, 209, 137, 111, 140, 112, 122, 122, 113, 110, 210, 211, 212, 111, 64, 112, 65, 66, 113, 216, 134, 135, 217, 249, 218, 219, 252, 267, 268,
  269, 220, 270, 256, 221, 225, 259, 11, 231, 263, 238, 12, 13, 14, 15, 136, 274, 275, 142, 143, 257, 16, 276, 17, 278, 293, 18, 19, 20, 21, 282, 61, 283, 271, 139, 141, 286, 145,
  294, 295, 290, 296, 300, 291, 122, 226, 301, 307, 11, 310, 29, 30, 12, 13, 14, 15, 313, 316, 321, 325, 302, 303, 16, 330, 17, 331, 46, 18, 19, 20, 21, 198, 55, 207, 264, 22, 23,
  24, 25, 26, 27, 62, 255, 232, 28, 284, 277, 298, 297, 340, 333, 29, 30, 344, 31, 328, 32, 33, 86, 11, 253, 329, 306, 12, 13, 14, 15, 0, 0, 0, 0, 0, 0, 16, 0, 17, 0, 0, 18, 19,
  20, 21, 0, 0, 0, 0, 22, 23, 24, 25, 26, 27, 0, 0, 0, 28, 0, 0, 0, 0, 0, 0, 29, 30, 0, 31, 11, 32, 33, 93, 12, 13, 14, 15, 0, 0, 0, 0, 0, 0, 16, 0, 17, 0, 0, 18, 19, 20, 21, 0,
  0, 0, 0, 22, 23, 24, 25, 26, 27, 0, 0, 0, 28, 0, 0, 0, 0, 0, 0, 29, 30, 0, 31, 114, 115, 33, 11, 120, 0, 0, 12, 13, 14, 15, 0, 0, 0, 0, 0, 0, 16, 0, 17, 0, 0, 18, 19, 20, 21, 0,
  0, 0, 0, 22, 23, 24, 25, 26, 27, 0, 0, 0, 121, 0, 0, 0, 0, 0, 0, 29, 30, 0, 31, 11, 32, 33, 0, 12, 13, 14, 15, 0, 0, 0, 0, 0, 0, 16, 0, 17, 0, 0, 18, 19, 20, 21, 0, 0, 0, 0, 22,
  23, 24, 25, 26, 27, 0, 0, 0, 28, 0, 0, 0, 0, 0, 0, 186, 30, 0, 31, 187, 32, 33, 11, 0, 0, 0, 12, 13, 14, 15, 0, 0, 0, 0, 0, 0, 16, 258, 17, 0, 0, 18, 19, 20, 21, 0, 0, 0, 0, 22,
  23, 24, 25, 26, 27, 0, 0, 0, 28, 0, 0, 0, 0, 0, 0, 29, 30, 0, 31, 11, 32, 33, 0, 12, 13, 14, 15, 0, 0, 0, 0, 0, 0, 16, 0, 17, 0, 0, 18, 19, 20, 21, 0, 0, 0, 0, 22, 23, 24, 25,
  26, 27, 0, 0, 0, 28, 0, 0, 0, 0, 0, 0, 29, 30, 0, 31, 11, 32, 33, 0, 12, 13, 14, 15, 0, 0, 0, 0, 0, 0, 16, 0, 17, 0, 0, 18, 19, 20, 21, 0, 0, 0, 0, 22, 23, 24, 25, 26, 27, 0, 0,
  0, 52, 0, 0, 0, 0, 0, 0, 53, 30, 0, 31, 11, 32, 33, 0, 12, 13, 14, 15, 0, 0, 0, 0, 0, 0, 16, 0, 17, 0, 0, 18, 19, 20, 21, 0, 0, 0, 0, 22, 23, 24, 25, 26, 27, 0, 0, 0, 28, 0, 0,
  0, 0, 0, 0, 29, 30, 0, 31, 11, 32, 89, 0, 12, 13, 14, 15, 0, 0, 0, 0, 0, 0, 16, 0, 17, 0, 0, 18, 19, 20, 21, 0, 0, 0, 0, 22, 23, 24, 25, 26, 27, 0, 0, 0, 28, 0, 0, 0, 0, 0, 0,
  29, 30, 0, 178, 11, 32, 33, 0, 12, 13, 14, 15, 0, 0, 0, 0, 0, 0, 16, 0, 17, 0, 0, 18, 19, 20, 21, 0, 0, 0, 0, 0, 164, 104, 105, 106, 107, 108, 109, 0, 110, 0, 0, 0, 111, 0, 112,
  29, 30, 113, 31, 0, 32, 89, 95, 96, 97, 98, 99, 100, 101, 102, 103, 239, 104, 105, 106, 107, 108, 109, 0, 110, 0, 0, 0, 111, 0, 112, 165, 0, 113, 0, 0, 0, 0, 95, 96, 97, 98, 99,
  100, 101, 102, 103, 266, 104, 105, 106, 107, 108, 109, 0, 110, 0, 0, 0, 111, 240, 112, 0, 0, 113, 0, 0, 0, 0, 95, 96, 97, 98, 99, 100, 101, 102, 103, 200, 104, 105, 106, 107,
  108, 109, 0, 110, 0, 0, 0, 111, 162, 112, 0, 0, 113, 0, 0, 0, 0, 95, 96, 97, 98, 99, 100, 101, 102, 103, 0, 104, 105, 106, 107, 108, 109, 159, 110, 0, 0, 0, 111, 0, 112, 0, 0,
  113, 0, 95, 96, 97, 98, 99, 100, 101, 102, 103, 0, 104, 105, 106, 107, 108, 109, 0, 110, 0, 0, 0, 111, 0, 112, 0, 0, 113, 262, 95, 96, 97, 98, 99, 100, 101, 102, 103, 0, 104,
  105, 106, 107, 108, 109, 0, 110, 0, 0, 0, 111, 0, 112, 0, 0, 113, 95, 96, 97, 98, 99, 100, 101, 102, 103, 0, 104, 105, 106, 107, 108, 109, 0, 110, 0, 0, 0, 111, 162, 112, 0, 0,
  113, 95, 96, 97, 98, 99, 100, 101, 102, 103, 0, 104, 105, 106, 107, 108, 109, 0, 110, 0, 0, 0, 111, 0, 112, 245, 0, 113, 95, 96, 97, 98, 99, 100, 101, 102, 103, 265, 104, 105,
  106, 107, 108, 109, 0, 110, 0, 0, 0, 111, 0, 112, 0, 0, 113, 95, 96, 97, 98, 99, 100, 101, 102, 103, 0, 104, 105, 106, 107, 108, 109, 0, 110, 0, 0, 0, 111, 0, 112, 0, 317, 113,
  95, 96, 97, 98, 99, 100, 101, 102, 103, 0, 104, 105, 106, 107, 108, 109, 0, 110, 0, 0, 0, 111, 0, 112, 0, 0, 113, 95, 96, 97, 98, 99, 100, 101, 102, 103, 0, 104, 127, 128, 129,
  130, 131, 0, 110, 0, 0, 0, 111, 0, 112, 0, 0, 113, 96, 97, 98, 99, 100, 101, 102, 103, 0, 104, 105, 106, 107, 108, 109, 0, 110, 0, 0, 0, 111, 0, 112, 0, 0, 113, 97, 98, 99, 100,
  101, 102, 103, 0, 104, 105, 106, 107, 108, 109, 0, 110, 0, 0, 0, 111, 0, 112, 0, 0, 113, -123, -123, -123, -123, -123, -123, 103, 0, 104, 105, 106, 107, 108, 109, 0, 110, 0, 0,
  0, 111, 0, 112, 0, 0, 113, 107, 108, 109, 0, 110, 0, 0, 0, 111, 0, 112, 0, 0, 113, 1, 2, 3, 4, 5, 6, 7, 8, 9,
];

/// ???
pub const YY_CHECK: [i16; 1236] = [
  1, 76, 3, 4, 12, 6, 7, 6, 7, 8, 199, 200, 6, 7, 8, 15, 17, 15, 3, 4, 0, 0, 0, 0, 32, 33, 34, 28, 0, 55, 31, 32, 15, 59, 18, 15, 15, 15, 15, 15, 0, 33, 26, 15, 45, 12, 58, 55,
  56, 58, 51, 52, 22, 23, 24, 25, 26, 27, 0, 59, 43, 59, 32, 33, 29, 32, 33, 43, 33, 39, 50, 51, 52, 52, 54, 54, 60, 266, 58, 58, 60, 60, 54, 63, 63, 63, 58, 33, 60, 56, 55, 63,
  285, 15, 95, 96, 97, 98, 99, 100, 101, 102, 33, 104, 105, 106, 107, 108, 109, 55, 111, 112, 63, 63, 115, 308, 309, 62, 119, 89, 121, 0, 315, 62, 55, 0, 127, 128, 129, 130, 131,
  132, 126, 132, 119, 62, 15, 0, 132, 332, 15, 334, 217, 15, 12, 115, 12, 0, 52, 342, 54, 21, 15, 55, 58, 58, 60, 29, 159, 63, 161, 55, 15, 164, 32, 33, 32, 33, 59, 60, 61, 50,
  51, 52, 54, 54, 177, 178, 58, 58, 60, 60, 33, 63, 63, 59, 60, 61, 56, 52, 56, 54, 12, 58, 62, 58, 62, 60, 199, 200, 63, 54, 62, 62, 62, 58, 58, 60, 60, 61, 63, 35, 32, 33, 15,
  216, 55, 30, 219, 22, 23, 24, 15, 26, 225, 55, 14, 228, 12, 35, 231, 14, 16, 17, 18, 19, 56, 238, 239, 59, 60, 14, 26, 55, 28, 59, 41, 31, 32, 33, 34, 47, 55, 47, 57, 65, 66,
  258, 68, 41, 41, 262, 41, 14, 265, 266, 55, 59, 59, 12, 55, 55, 56, 16, 17, 18, 19, 43, 33, 14, 20, 282, 283, 26, 43, 28, 43, 2, 31, 32, 33, 34, 119, 6, 132, 233, 39, 40, 41,
  42, 43, 44, 8, 222, 161, 48, 255, 242, 277, 275, 333, 322, 55, 56, 343, 58, 317, 60, 61, 62, 12, 220, 318, 287, 16, 17, 18, 19, -1, -1, -1, -1, -1, -1, 26, -1, 28, -1, -1, 31,
  32, 33, 34, -1, -1, -1, -1, 39, 40, 41, 42, 43, 44, -1, -1, -1, 48, -1, -1, -1, -1, -1, -1, 55, 56, -1, 58, 12, 60, 61, 62, 16, 17, 18, 19, -1, -1, -1, -1, -1, -1, 26, -1, 28,
  -1, -1, 31, 32, 33, 34, -1, -1, -1, -1, 39, 40, 41, 42, 43, 44, -1, -1, -1, 48, -1, -1, -1, -1, -1, -1, 55, 56, -1, 58, 59, 60, 61, 12, 13, -1, -1, 16, 17, 18, 19, -1, -1, -1,
  -1, -1, -1, 26, -1, 28, -1, -1, 31, 32, 33, 34, -1, -1, -1, -1, 39, 40, 41, 42, 43, 44, -1, -1, -1, 48, -1, -1, -1, -1, -1, -1, 55, 56, -1, 58, 12, 60, 61, -1, 16, 17, 18, 19,
  -1, -1, -1, -1, -1, -1, 26, -1, 28, -1, -1, 31, 32, 33, 34, -1, -1, -1, -1, 39, 40, 41, 42, 43, 44, -1, -1, -1, 48, -1, -1, -1, -1, -1, -1, 55, 56, -1, 58, 59, 60, 61, 12, -1,
  -1, -1, 16, 17, 18, 19, -1, -1, -1, -1, -1, -1, 26, 27, 28, -1, -1, 31, 32, 33, 34, -1, -1, -1, -1, 39, 40, 41, 42, 43, 44, -1, -1, -1, 48, -1, -1, -1, -1, -1, -1, 55, 56, -1,
  58, 12, 60, 61, -1, 16, 17, 18, 19, -1, -1, -1, -1, -1, -1, 26, -1, 28, -1, -1, 31, 32, 33, 34, -1, -1, -1, -1, 39, 40, 41, 42, 43, 44, -1, -1, -1, 48, -1, -1, -1, -1, -1, -1,
  55, 56, -1, 58, 12, 60, 61, -1, 16, 17, 18, 19, -1, -1, -1, -1, -1, -1, 26, -1, 28, -1, -1, 31, 32, 33, 34, -1, -1, -1, -1, 39, 40, 41, 42, 43, 44, -1, -1, -1, 48, -1, -1, -1,
  -1, -1, -1, 55, 56, -1, 58, 12, 60, 61, -1, 16, 17, 18, 19, -1, -1, -1, -1, -1, -1, 26, -1, 28, -1, -1, 31, 32, 33, 34, -1, -1, -1, -1, 39, 40, 41, 42, 43, 44, -1, -1, -1, 48,
  -1, -1, -1, -1, -1, -1, 55, 56, -1, 58, 12, 60, 61, -1, 16, 17, 18, 19, -1, -1, -1, -1, -1, -1, 26, -1, 28, -1, -1, 31, 32, 33, 34, -1, -1, -1, -1, 39, 40, 41, 42, 43, 44, -1,
  -1, -1, 48, -1, -1, -1, -1, -1, -1, 55, 56, -1, 58, 12, 60, 61, -1, 16, 17, 18, 19, -1, -1, -1, -1, -1, -1, 26, -1, 28, -1, -1, 31, 32, 33, 34, -1, -1, -1, -1, -1, 15, 47, 48,
  49, 50, 51, 52, -1, 54, -1, -1, -1, 58, -1, 60, 55, 56, 63, 58, -1, 60, 61, 37, 38, 39, 40, 41, 42, 43, 44, 45, 15, 47, 48, 49, 50, 51, 52, -1, 54, -1, -1, -1, 58, -1, 60, 61,
  -1, 63, -1, -1, -1, -1, 37, 38, 39, 40, 41, 42, 43, 44, 45, 15, 47, 48, 49, 50, 51, 52, -1, 54, -1, -1, -1, 58, 59, 60, -1, -1, 63, -1, -1, -1, -1, 37, 38, 39, 40, 41, 42, 43,
  44, 45, 15, 47, 48, 49, 50, 51, 52, -1, 54, -1, -1, -1, 58, 59, 60, -1, -1, 63, -1, -1, -1, -1, 37, 38, 39, 40, 41, 42, 43, 44, 45, -1, 47, 48, 49, 50, 51, 52, 25, 54, -1, -1,
  -1, 58, -1, 60, -1, -1, 63, -1, 37, 38, 39, 40, 41, 42, 43, 44, 45, -1, 47, 48, 49, 50, 51, 52, -1, 54, -1, -1, -1, 58, -1, 60, -1, -1, 63, 36, 37, 38, 39, 40, 41, 42, 43, 44,
  45, -1, 47, 48, 49, 50, 51, 52, -1, 54, -1, -1, -1, 58, -1, 60, -1, -1, 63, 37, 38, 39, 40, 41, 42, 43, 44, 45, -1, 47, 48, 49, 50, 51, 52, -1, 54, -1, -1, -1, 58, 59, 60, -1,
  -1, 63, 37, 38, 39, 40, 41, 42, 43, 44, 45, -1, 47, 48, 49, 50, 51, 52, -1, 54, -1, -1, -1, 58, -1, 60, 61, -1, 63, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
  52, -1, 54, -1, -1, -1, 58, -1, 60, -1, -1, 63, 37, 38, 39, 40, 41, 42, 43, 44, 45, -1, 47, 48, 49, 50, 51, 52, -1, 54, -1, -1, -1, 58, -1, 60, -1, 62, 63, 37, 38, 39, 40, 41,
  42, 43, 44, 45, -1, 47, 48, 49, 50, 51, 52, -1, 54, -1, -1, -1, 58, -1, 60, -1, -1, 63, 37, 38, 39, 40, 41, 42, 43, 44, 45, -1, 47, 48, 49, 50, 51, 52, -1, 54, -1, -1, -1, 58,
  -1, 60, -1, -1, 63, 38, 39, 40, 41, 42, 43, 44, 45, -1, 47, 48, 49, 50, 51, 52, -1, 54, -1, -1, -1, 58, -1, 60, -1, -1, 63, 39, 40, 41, 42, 43, 44, 45, -1, 47, 48, 49, 50, 51,
  52, -1, 54, -1, -1, -1, 58, -1, 60, -1, -1, 63, 39, 40, 41, 42, 43, 44, 45, -1, 47, 48, 49, 50, 51, 52, -1, 54, -1, -1, -1, 58, -1, 60, -1, -1, 63, 50, 51, 52, -1, 54, -1, -1,
  -1, 58, -1, 60, -1, -1, 63, 3, 4, 5, 6, 7, 8, 9, 10, 11,
];

/// `YY_R1[YYN]` - symbol number of symbol that rule YYN derives.
pub const YY_R1: [u8; 189] = [
  0, 64, 65, 65, 65, 65, 66, 65, 65, 65, 65, 65, 67, 67, 68, 68, 68, 70, 69, 69, 71, 69, 72, 69, 73, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 74, 69,
  69, 69, 69, 69, 69, 69, 69, 75, 75, 76, 76, 76, 77, 77, 78, 79, 79, 79, 79, 79, 79, 79, 80, 80, 81, 81, 81, 81, 81, 81, 81, 82, 83, 83, 83, 83, 83, 84, 84, 84, 84, 84, 85, 86,
  86, 87, 87, 88, 88, 88, 88, 89, 88, 91, 90, 92, 92, 93, 94, 94, 95, 95, 96, 97, 97, 98, 98, 99, 99, 99, 100, 101, 102, 102, 103, 104, 104, 105, 105, 106, 106, 107, 106, 108,
  106, 106, 109, 106, 110, 112, 111, 113, 113, 114, 115, 114, 116, 117, 116, 118, 118, 120, 121, 119, 122, 122, 123, 123, 125, 126, 124, 128, 127, 129, 130, 129, 131, 132, 131,
  134, 133, 133, 135, 135, 136, 137, 137, 137, 137, 137, 138, 138, 138, 138, 138, 139, 139, 139, 140, 139, 142, 143, 141, 144, 141,
];

/// `YY_R2[YYN]` - number of symbols on the right hand side of rule YYN.
pub const YY_R2: [i8; 189] = [
  0, 2, 2, 2, 2, 2, 0, 3, 2, 2, 2, 2, 1, 1, 1, 1, 1, 0, 5, 6, 0, 5, 0, 5, 0, 6, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 2, 0, 5, 3, 4, 3, 1, 1, 1, 3, 3, 1, 1, 4, 1, 3, 1, 4,
  3, 3, 3, 3, 3, 2, 1, 3, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 3, 3, 3, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 4, 0, 3, 1, 2, 3, 1, 3, 1, 1, 2, 1, 2, 1, 3, 1, 1, 1, 2, 3, 1, 3,
  2, 1, 3, 3, 1, 1, 1, 0, 5, 0, 5, 3, 0, 6, 2, 0, 4, 1, 3, 1, 0, 3, 1, 0, 4, 3, 1, 0, 0, 5, 1, 3, 3, 1, 0, 0, 5, 0, 5, 1, 0, 3, 1, 0, 4, 0, 4, 1, 2, 1, 2, 2, 2, 3, 3, 3, 1, 1, 2,
  2, 2, 1, 1, 2, 0, 5, 0, 0, 5, 0, 2,
];

///Trait for reduce action definitions.
pub trait ReduceActions {
  fn action_addition(&mut self) -> Result<()>;
  fn action_between(&mut self) -> Result<()>;
  fn action_between_begin(&mut self) -> Result<()>;
  fn action_built_in_type_name(&mut self) -> Result<()>;
  fn action_comparison_eq(&mut self) -> Result<()>;
  fn action_comparison_ge(&mut self) -> Result<()>;
  fn action_comparison_gt(&mut self) -> Result<()>;
  fn action_comparison_in(&mut self) -> Result<()>;
  fn action_comparison_le(&mut self) -> Result<()>;
  fn action_comparison_lt(&mut self) -> Result<()>;
  fn action_comparison_ne(&mut self) -> Result<()>;
  fn action_comparison_unary_eq(&mut self) -> Result<()>;
  fn action_comparison_unary_ge(&mut self) -> Result<()>;
  fn action_comparison_unary_gt(&mut self) -> Result<()>;
  fn action_comparison_unary_le(&mut self) -> Result<()>;
  fn action_comparison_unary_lt(&mut self) -> Result<()>;
  fn action_comparison_unary_ne(&mut self) -> Result<()>;
  fn action_conjunction(&mut self) -> Result<()>;
  fn action_context_begin(&mut self) -> Result<()>;
  fn action_context_end(&mut self) -> Result<()>;
  fn action_context_entry(&mut self) -> Result<()>;
  fn action_context_entry_tail(&mut self) -> Result<()>;
  fn action_context_type_entry(&mut self) -> Result<()>;
  fn action_context_type_entry_tail(&mut self) -> Result<()>;
  fn action_disjunction(&mut self) -> Result<()>;
  fn action_division(&mut self) -> Result<()>;
  fn action_empty_context(&mut self) -> Result<()>;
  fn action_every(&mut self) -> Result<()>;
  fn action_every_begin(&mut self) -> Result<()>;
  fn action_exponentiation(&mut self) -> Result<()>;
  fn action_expression_list_tail(&mut self) -> Result<()>;
  fn action_filter(&mut self) -> Result<()>;
  fn action_for(&mut self) -> Result<()>;
  fn action_for_begin(&mut self) -> Result<()>;
  fn action_formal_parameter_with_type(&mut self) -> Result<()>;
  fn action_formal_parameter_without_type(&mut self) -> Result<()>;
  fn action_formal_parameters_begin(&mut self) -> Result<()>;
  fn action_formal_parameters_empty(&mut self) -> Result<()>;
  fn action_formal_parameters_first(&mut self) -> Result<()>;
  fn action_formal_parameters_tail(&mut self) -> Result<()>;
  fn action_function_body(&mut self) -> Result<()>;
  fn action_function_body_external(&mut self) -> Result<()>;
  fn action_function_definition(&mut self) -> Result<()>;
  fn action_function_invocation(&mut self) -> Result<()>;
  fn action_function_invocation_no_parameters(&mut self) -> Result<()>;
  fn action_function_type(&mut self) -> Result<()>;
  fn action_function_type_parameters_empty(&mut self) -> Result<()>;
  fn action_function_type_parameters_tail(&mut self) -> Result<()>;
  fn action_if(&mut self) -> Result<()>;
  fn action_instance_of(&mut self) -> Result<()>;
  fn action_interval(&mut self) -> Result<()>;
  fn action_interval_empty_end(&mut self) -> Result<()>;
  fn action_interval_empty_start(&mut self) -> Result<()>;
  fn action_interval_end(&mut self) -> Result<()>;
  fn action_interval_start(&mut self) -> Result<()>;
  fn action_iteration_context_value_range(&mut self) -> Result<()>;
  fn action_iteration_context_value_single(&mut self) -> Result<()>;
  fn action_iteration_context_variable_name(&mut self) -> Result<()>;
  fn action_iteration_context_variable_name_begin(&mut self) -> Result<()>;
  fn action_iteration_contexts_tail(&mut self) -> Result<()>;
  fn action_key_name(&mut self) -> Result<()>;
  fn action_key_string(&mut self) -> Result<()>;
  fn action_list(&mut self) -> Result<()>;
  fn action_list_empty(&mut self) -> Result<()>;
  fn action_list_tail(&mut self) -> Result<()>;
  fn action_list_type(&mut self) -> Result<()>;
  fn action_literal_at(&mut self) -> Result<()>;
  fn action_literal_boolean(&mut self) -> Result<()>;
  fn action_literal_date_time(&mut self) -> Result<()>;
  fn action_literal_null(&mut self) -> Result<()>;
  fn action_literal_numeric(&mut self) -> Result<()>;
  fn action_literal_string(&mut self) -> Result<()>;
  fn action_multiplication(&mut self) -> Result<()>;
  fn action_name(&mut self) -> Result<()>;
  fn action_named_parameter(&mut self) -> Result<()>;
  fn action_named_parameters_tail(&mut self) -> Result<()>;
  fn action_negation(&mut self) -> Result<()>;
  fn action_path(&mut self) -> Result<()>;
  fn action_positional_parameters_tail(&mut self) -> Result<()>;
  fn action_qualified_name(&mut self) -> Result<()>;
  fn action_qualified_name_tail(&mut self) -> Result<()>;
  fn action_quantified_expression(&mut self) -> Result<()>;
  fn action_quantified_expression_variable_name(&mut self) -> Result<()>;
  fn action_quantified_expression_variable_name_begin(&mut self) -> Result<()>;
  fn action_quantified_expressions_tail(&mut self) -> Result<()>;
  fn action_range_literal(&mut self) -> Result<()>;
  fn action_range_literal_empty_end(&mut self) -> Result<()>;
  fn action_range_literal_empty_start(&mut self) -> Result<()>;
  fn action_range_literal_end(&mut self) -> Result<()>;
  fn action_range_literal_start(&mut self) -> Result<()>;
  fn action_range_type(&mut self) -> Result<()>;
  fn action_some(&mut self) -> Result<()>;
  fn action_some_begin(&mut self) -> Result<()>;
  fn action_subtraction(&mut self) -> Result<()>;
  fn action_type_name(&mut self) -> Result<()>;
  fn action_unary_tests_begin(&mut self) -> Result<()>;
  fn action_unary_tests_irrelevant(&mut self) -> Result<()>;
  fn action_unary_tests_negated(&mut self) -> Result<()>;
}

/// Calls requested reduce action.
pub fn reduce(reduce_actions: &mut impl ReduceActions, rule_number: i16) -> Result<()> {
  match rule_number {
    6 => reduce_actions.action_unary_tests_begin(),
    17 => reduce_actions.action_for_begin(),
    18 => reduce_actions.action_for(),
    19 => reduce_actions.action_if(),
    20 => reduce_actions.action_some_begin(),
    21 => reduce_actions.action_some(),
    22 => reduce_actions.action_every_begin(),
    23 => reduce_actions.action_every(),
    24 => reduce_actions.action_between_begin(),
    25 => reduce_actions.action_between(),
    26 => reduce_actions.action_disjunction(),
    27 => reduce_actions.action_conjunction(),
    28 => reduce_actions.action_comparison_eq(),
    29 => reduce_actions.action_comparison_ne(),
    30 => reduce_actions.action_comparison_lt(),
    31 => reduce_actions.action_comparison_le(),
    32 => reduce_actions.action_comparison_gt(),
    33 => reduce_actions.action_comparison_ge(),
    34 => reduce_actions.action_comparison_in(),
    35 => reduce_actions.action_comparison_in(),
    36 => reduce_actions.action_addition(),
    37 => reduce_actions.action_subtraction(),
    38 => reduce_actions.action_multiplication(),
    39 => reduce_actions.action_division(),
    40 => reduce_actions.action_exponentiation(),
    41 => reduce_actions.action_negation(),
    42 => reduce_actions.action_type_name(),
    43 => reduce_actions.action_instance_of(),
    44 => reduce_actions.action_path(),
    45 => reduce_actions.action_filter(),
    49 => reduce_actions.action_name(),
    51 => reduce_actions.action_expression_list_tail(),
    52 => reduce_actions.action_expression_list_tail(),
    53 => reduce_actions.action_unary_tests_irrelevant(),
    54 => reduce_actions.action_unary_tests_negated(),
    56 => reduce_actions.action_expression_list_tail(),
    57 => reduce_actions.action_expression_list_tail(),
    58 => reduce_actions.action_expression_list_tail(),
    59 => reduce_actions.action_addition(),
    60 => reduce_actions.action_subtraction(),
    61 => reduce_actions.action_multiplication(),
    62 => reduce_actions.action_division(),
    63 => reduce_actions.action_exponentiation(),
    64 => reduce_actions.action_negation(),
    66 => reduce_actions.action_expression_list_tail(),
    67 => reduce_actions.action_expression_list_tail(),
    68 => reduce_actions.action_comparison_unary_lt(),
    69 => reduce_actions.action_comparison_unary_le(),
    70 => reduce_actions.action_comparison_unary_gt(),
    71 => reduce_actions.action_comparison_unary_ge(),
    72 => reduce_actions.action_comparison_unary_eq(),
    73 => reduce_actions.action_comparison_unary_ne(),
    75 => reduce_actions.action_interval(),
    76 => reduce_actions.action_interval_empty_start(),
    77 => reduce_actions.action_interval_empty_start(),
    78 => reduce_actions.action_interval_start(),
    79 => reduce_actions.action_interval_start(),
    80 => reduce_actions.action_interval_start(),
    81 => reduce_actions.action_interval_empty_end(),
    82 => reduce_actions.action_interval_empty_end(),
    83 => reduce_actions.action_interval_end(),
    84 => reduce_actions.action_interval_end(),
    85 => reduce_actions.action_interval_end(),
    90 => reduce_actions.action_literal_null(),
    91 => reduce_actions.action_literal_numeric(),
    92 => reduce_actions.action_literal_string(),
    93 => reduce_actions.action_literal_boolean(),
    94 => reduce_actions.action_literal_at(),
    95 => reduce_actions.action_literal_date_time(),
    97 => reduce_actions.action_context_begin(),
    98 => reduce_actions.action_context_end(),
    99 => reduce_actions.action_empty_context(),
    100 => reduce_actions.action_context_entry_tail(),
    101 => reduce_actions.action_context_entry(),
    103 => reduce_actions.action_context_entry_tail(),
    104 => reduce_actions.action_key_name(),
    105 => reduce_actions.action_key_string(),
    106 => reduce_actions.action_list(),
    107 => reduce_actions.action_list_empty(),
    108 => reduce_actions.action_list_tail(),
    110 => reduce_actions.action_list_tail(),
    111 => reduce_actions.action_function_invocation_no_parameters(),
    112 => reduce_actions.action_function_invocation(),
    113 => reduce_actions.action_function_invocation(),
    114 => reduce_actions.action_named_parameters_tail(),
    115 => reduce_actions.action_named_parameter(),
    117 => reduce_actions.action_named_parameters_tail(),
    118 => reduce_actions.action_positional_parameters_tail(),
    120 => reduce_actions.action_positional_parameters_tail(),
    121 => reduce_actions.action_qualified_name_tail(),
    122 => reduce_actions.action_qualified_name(),
    123 => reduce_actions.action_built_in_type_name(),
    125 => reduce_actions.action_type_name(),
    126 => reduce_actions.action_list_type(),
    127 => reduce_actions.action_type_name(),
    128 => reduce_actions.action_range_type(),
    130 => reduce_actions.action_type_name(),
    131 => reduce_actions.action_function_type(),
    132 => reduce_actions.action_context_type_entry_tail(),
    133 => reduce_actions.action_type_name(),
    134 => reduce_actions.action_context_type_entry(),
    136 => reduce_actions.action_context_type_entry_tail(),
    137 => reduce_actions.action_function_type_parameters_empty(),
    138 => reduce_actions.action_type_name(),
    139 => reduce_actions.action_function_type_parameters_tail(),
    141 => reduce_actions.action_type_name(),
    142 => reduce_actions.action_function_type_parameters_tail(),
    143 => reduce_actions.action_iteration_contexts_tail(),
    144 => reduce_actions.action_iteration_contexts_tail(),
    145 => reduce_actions.action_iteration_context_variable_name_begin(),
    146 => reduce_actions.action_iteration_context_variable_name(),
    148 => reduce_actions.action_iteration_context_value_single(),
    149 => reduce_actions.action_iteration_context_value_range(),
    150 => reduce_actions.action_quantified_expressions_tail(),
    151 => reduce_actions.action_quantified_expressions_tail(),
    152 => reduce_actions.action_quantified_expression_variable_name_begin(),
    153 => reduce_actions.action_quantified_expression_variable_name(),
    154 => reduce_actions.action_quantified_expression(),
    155 => reduce_actions.action_formal_parameters_begin(),
    156 => reduce_actions.action_function_definition(),
    157 => reduce_actions.action_formal_parameters_empty(),
    158 => reduce_actions.action_formal_parameters_first(),
    161 => reduce_actions.action_formal_parameters_tail(),
    163 => reduce_actions.action_type_name(),
    164 => reduce_actions.action_formal_parameter_with_type(),
    165 => reduce_actions.action_formal_parameter_without_type(),
    166 => reduce_actions.action_function_body_external(),
    167 => reduce_actions.action_function_body(),
    168 => reduce_actions.action_range_literal(),
    169 => reduce_actions.action_range_literal_empty_start(),
    170 => reduce_actions.action_range_literal_empty_start(),
    171 => reduce_actions.action_range_literal_start(),
    172 => reduce_actions.action_range_literal_start(),
    173 => reduce_actions.action_range_literal_start(),
    174 => reduce_actions.action_range_literal_empty_end(),
    175 => reduce_actions.action_range_literal_empty_end(),
    176 => reduce_actions.action_range_literal_end(),
    177 => reduce_actions.action_range_literal_end(),
    178 => reduce_actions.action_range_literal_end(),
    179 => reduce_actions.action_literal_numeric(),
    180 => reduce_actions.action_literal_string(),
    181 => reduce_actions.action_literal_at(),
    182 => reduce_actions.action_literal_date_time(),
    183 => reduce_actions.action_function_invocation(),
    184 => reduce_actions.action_literal_string(),
    185 => reduce_actions.action_named_parameter(),
    186 => reduce_actions.action_named_parameters_tail(),
    187 => reduce_actions.action_literal_string(),
    188 => reduce_actions.action_positional_parameters_tail(),
    _ => Ok(()),
  }
}
